### ISSUE TITLE
TypeError: function() got an unexpected keyword argument 'broadcast_inputs'

### ISSUE THREAD

**Issue by Nqabz** [astooke/synkhronos#10]
In an attempt to test demo1.py I am encountering an error that suggest that the broadcast_inputs keyword is not expected in this function. Could you confirm what changes I should make.
 ```
 File "/home/synkhronos/demos/demo1.py", line 23, in <module>
    f_synk = synk.function([x, y], z, broadcast_inputs=[y])
  File "/opt/conda/lib/python3.5/site-packages/synkhronos/function_builder.py", line 45, in function
    **kwargs,
TypeError: function() got an unexpected keyword argument 'broadcast_inputs'
```
I installed the code from here: `git clone https://github.com/astooke/synkhronos` and I am testing from an NVIDIA DGX1 docker container.

**Comment by astooke** [comment]
Hi, sorry the demos were leftover from a previous version.

I have just pushed some new demos, demo_1 through demo_4, please give those a try!

**Comment by Nqabz** [comment]
I will give the new demos a try tomorrow. Thanks for getting back to me.
